name: Build

on:
  push:
    branches:
      - develop


jobs:
  build:
    name: Build
    runs-on: [moon]
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shell command
        run: |
          echo "HI" 
          cd /home/ubuntu/strapi
          git pull origin develop
          yarn build 
          cd examples/getstarted/ 
          pm2 restart ecosystem.config.js --only strapi-getstarted
          pm2 save



     

      
     
      
